### ISSUE TITLE
Roadmap to 0.1.0 release

### ISSUE THREAD

**Issue by AGausmann** [AGausmann/webgl_loader#1]
Here's a list of features that I would like to have completed for 0.1.0:

- [x] Context management
    - [ ] More explicit version selection (auto-detected right now, but there should be a mapping from the GL version to the required WebGL)
- [ ] WebGL 1.0 / OpenGL ES 2.0 support
    - [x] Direct mapping of available functions
    - [ ] Full emulation
- [ ] WebGL 2.0 / OpenGL ES 3.2 support
    - [ ] Direct mapping
    - [ ] Full emulation
